name: Create Docker Container 

on: [push]

jobs:
  mlops-container:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./week_6_github_actions
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Build container
        run: |
          docker newtwork create data
          docker build --tag inference:latest .
          docker run -d -p 8080:8080 --network data inference:latest